# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
env:
  - CGO_ENABLED=0
builds:
  - targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^style'
      - '^refactor'
      - '^build'
      - '^ci'
      - '^chore(release)'